# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-16 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='author_id',
            field=models.IntegerField(default=None, null=True, unique=True),
        ),
    ]
