# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-19 03:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20161017_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='author_id',
            field=models.IntegerField(default=None, unique=True),
        ),
    ]
